# https://github.com/lowlighter/metrics
name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_followup: yes
          plugin_followup_sections: repositories, user 
          
          token: ${{ secrets.METRICS_TOKEN }}

